package base.types;

public enum SqlType
{
	NUMERIC, DECIMAL, BIT, TINYINT, SMALLINT, INTEGER, BIGINT, REAL, FLOAT, DOUBLE, BINARY, VARBINARY, LONGVARBINARY, DATE, TIME, TIMESTAMP, BLOB, CLOB, NCLOB, NCHAR, NVARCHAR, CHAR, VARCHAR, LONGVARCHAR, NULL, OTHER, JAVA_OBJECT, DISTINCT, STRUCT, ARRAY, REF, DATALINK, BOOLEAN, ROWID, SQLXML
}
